# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 20:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1100)),
                ('logotype', models.FileField(upload_to=b'')),
                ('area_of_business', models.CharField(choices=[(b'finance', b'Finance'), (b'appdev', b'App Development'), (b'consulting', b'Consulting'), (b'entertainment', b'Entertainment'), (b'comm', b'Communication'), (b'it', b'IT Services'), (b'prodev', b'Product Development'), (b'info', b'Information'), (b'edu', b'Education'), (b'data', b'Data & Search'), (b'fash', b'Fashion'), (b'sec', b'Security'), (b'man', b'Management')], default=b'Pick one', max_length=100)),
                ('employees', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('first_time_at_fair', models.BooleanField(default=True)),
                ('billing_address', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=500)),
                ('priority', models.CharField(choices=[(b'low', b'LOW'), (b'mid', b'MID'), (b'high', b'HIGH')], default=(b'low', b'LOW'), max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True)),
                ('STATUS', models.CharField(choices=[(b'notcontacted', b'Not Contacted'), (b'contacted', b'Contacted - Waiting to sign up'), (b'signedup', b'Signed Up - Waiting for contract to be signed'), (b'contractsigned', b'Contract Signed'), (b'dec', b'Declined')], default=(b'notcontacted', b'Not Contacted'), max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Company')),
            ],
        ),
    ]
