# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[(b'lunch', b'Lunch lecture'), (b'pub', b'Pub'), (b'other', b'Other')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Company')),
            ],
        ),
    ]
