# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('email_address', models.CharField(max_length=100)),
                ('cell_phone_number', models.CharField(max_length=50)),
                ('other_phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Company')),
            ],
        ),
    ]
