# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('max_number_of_companies', models.PositiveIntegerField()),
            ],
        ),
    ]
