# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_fair'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair',
            name='companies',
            field=models.ManyToManyField(to='signup.Company'),
        ),
    ]
